# Generated by Django 6.0.7 on 2026-07-22 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wardrobe/')),
                ('category', models.CharField(max_length=30)),
                ('category_confidence', models.FloatField()),
                ('texture', models.CharField(max_length=30)),
                ('texture_confidence', models.FloatField()),
                ('season', models.CharField(max_length=20)),
                ('season_confidence', models.FloatField()),
                ('season_probs', models.JSONField()),
                ('dominant_colors', models.JSONField()),
                ('mask_found', models.BooleanField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
