# Generated by Django 6.0.2 on 2026-07-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_wardrobeitem_favorite_wardrobeitem_processed_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='outfit',
            name='style_preference',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='outfit',
            name='temp_c',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
