# Generated by Django 6.0.2 on 2026-08-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0005_chatsession_chatmessage_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfit',
            old_name='city',
            new_name='country',
        ),
        migrations.AddField(
            model_name='outfit',
            name='location_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='outfit',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
