# Generated by Django 6.0.2 on 2026-08-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0007_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeitem',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='done', max_length=20),
        ),
    ]
