# Generated by Django 6.0.2 on 2026-08-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0009_chatsession_last_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_temp_c',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
