# Generated by Django 6.0.2 on 2026-08-15 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0010_chatsession_last_temp_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeitem',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='possible_duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wardrobe.wardrobeitem'),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('duplicate_review', 'Possible Duplicate')], default='done', max_length=20),
        ),
    ]
