# Generated by Django 6.0.2 on 2026-08-15 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0011_wardrobeitem_image_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='bottom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wardrobe.wardrobeitem'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='jacket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wardrobe.wardrobeitem'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wardrobe.wardrobeitem'),
        ),
    ]
