# Generated by Django 6.0.2 on 2026-08-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0012_alter_outfit_bottom_alter_outfit_jacket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_style_preference',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
