# Generated by Django 6.0.2 on 2026-08-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0012_tryonresult'),
        ('wardrobe', '0013_chatsession_last_style_preference'),
    ]

    operations = [
    ]
