# Generated by Django 6.0.2 on 2026-08-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0014_merge_20260816_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_recommendation_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
