# Generated by Django 6.0.2 on 2026-08-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0008_wardrobeitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_intent',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_outfit_index',
            field=models.IntegerField(default=0),
        ),
    ]
